Repository Sunil0517/Random-quotes-generator, pull requests merged in 2022-10, with the labels that each got.

#1 Update randomQuote.html
  randomQuote.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2 quote_change.html
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted

#3 added a new quotes
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted

#4 Added a quote.
  randomQuote.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#6 ADDED TWO QUOTE
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted

#5 accept kar suresh chhichora
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted

#7 accept request
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update randomQuote.html
  randomQuote.html
Labels: hacktoberfest, hacktoberfest-accepted
